TEHIK-EE/tedi-design-system

- libs/react-components/community/src/components/layout/breadcrumbs/breadcrumbs.module.scss
- libs/react-components/community/src/components/layout/breadcrumbs/crumb/crumb.tsx
https://github.com/TEHIK-EE/tedi-design-system/issues/45
> fix(Breadcrumbs): Make last element text

- libs/react-components/community/src/components/form/file-upload/file-upload.stories.tsx
- libs/react-components/community/src/components/form/file-upload/file-upload.tsx
- libs/react-components/community/src/providers/label-provider/labels-map.ts
https://github.com/TEHIK-EE/tedi-design-system/issues/54
> feat(FileUpload): added optional size checking and callback

- libs/react-components/community/src/components/table/components/pagination/pagination.tsx
https://github.com/TEHIK-EE/tedi-design-system/issues/83
https://kristiina-richards.github.io/tedi-design-system/feature/table-rows/iframe.html?args=&id=community-components-table--default&viewMode=story
> feat(table): add options for 50 and 100 rows for tables

- libs/react-components/community/src/components/layout/footer/footer.tsx
- libs/react-components/community/src/components/layout/sidenav/sidenav.tsx
https://kristiina-richards.github.io/tedi-design-system/bug/layout-wcag-fixes/?path=/story/community-components-layout--default
> fix(layout): fix role for sidenav and add break-all to footer links

- libs/react-components/community/src/components/form/check/check.tsx
- libs/react-components/community/src/components/form/radio/radio.tsx
https://kristiina-richards.github.io/tedi-design-system/bug/choicegroup-wcag/?path=/docs/community-components-form-choicegroup--docs
> fix(choice-group): fix radio and check button screenreader bug

- libs/react-components/community/src/components/accordion/accordion-item-header/accordion-item-header.tsx
- libs/react-components/community/src/components/accordion/accordion.stories.tsx
- libs/react-components/community/src/components/card/card-header/card-header.tsx
- libs/react-components/community/src/components/card/card.module.scss
- libs/react-components/community/src/components/commonTypes.tsx
add muted color for accordion header background
> feat(accordion, card-header): add muted color for accordion header background

- libs/react-components/community/src/components/form/textfield/textfield.module.scss
- libs/react-components/community/src/components/form/textfield/textfield.stories.tsx
- libs/react-components/community/src/components/form/textfield/textfield.tsx
- libs/react-components/community/src/providers/label-provider/labels-map.ts
Large TextField - https://harlespilter.github.io/tedi-design-system/feature/89-text-field-clear/?path=/story/community-components-form-textfield--large
Clear TextField - https://harlespilter.github.io/tedi-design-system/feature/89-text-field-clear/?path=/story/community-components-form-textfield--clearable
Closes https://github.com/TEHIK-EE/tedi-design-system/issues/89
> feat(TextField): #89 - Add isClearable and large option to TextField

- libs/react-components/community/src/components/form/pickers/datepicker/datepicker.tsx
- libs/react-components/community/src/components/form/pickers/datetimepicker/datetimepicker.tsx
- libs/react-components/community/src/components/form/pickers/timepicker/timepicker.tsx
- libs/react-components/community/src/components/form/textfield/textfield.tsx
https://harlespilter.github.io/tedi-design-system/bugfix/94-picker-clear/?path=/story/community-components-form-pickers-datepicker--default&args=isClearable:!true
Closes #94
> fix(pickers): #94 - Clear picker value with the clear button

- libs/react-components/community/src/components/ellipsis/ellipsis.stories.tsx
- libs/react-components/community/src/components/ellipsis/ellipsis.tsx
https://harlespilter.github.io/tedi-design-system/bugfix/92-ellips/?path=/story/community-components-ellipsis--responsive-example
Closes #92
> fix(ellipsis): #92 - Add responsivness support for ellipsis

- libs/react-components/community/src/components/form/pickers/datepicker/datepicker.stories.tsx
- libs/react-components/community/src/components/form/pickers/datepicker/datepicker.tsx
- libs/react-components/community/src/components/form/pickers/datetimepicker/datetimepicker.stories.tsx
- libs/react-components/community/src/components/form/pickers/datetimepicker/datetimepicker.tsx
https://harlespilter.github.io/tedi-design-system/feature/99-reference-date/?path=/story/community-components-form-pickers-datepicker--reference-date
https://harlespilter.github.io/tedi-design-system/feature/99-reference-date/?path=/story/community-components-form-pickers-datetimepicker--reference-date
Closes #99
> feat(pickers): #99 - Added referenceDate prop to the pickers

- libs/react-components/community/src/components/ellipsis/ellipsis.stories.tsx
- libs/react-components/community/src/components/ellipsis/ellipsis.tsx
> feat(ellipsis): add showTooltip property #169

- libs/react-components/community/src/components/anchor/anchor.stories.tsx
- libs/react-components/community/src/components/button-content/button-content.module.scss
> fix(button, anchor): inline link style button icon #216

- libs/react-components/community/src/components/button-content/button-content.module.scss
- libs/react-components/community/src/components/button-content/button-content.tsx
caused by #216 
example of broken loading state:
https://github.tehik.ee/tedi-design-system/rc/?path=/story/community-button--link
Fixed:
https://github.tehik.ee/tedi-design-system/fix/loading-icons-216/?path=/story/community-button--link
> fix(button): fix loading icons #216

- libs/react-components/community/src/components/accordion/accordion-item-header/accordion-item-header.tsx
- libs/react-components/community/src/components/toggle-open/toggle-open.tsx
Reverts TEHIK-EE/tedi-design-system#171
> Revert " feat(toggleOpen): #102 - Change ToggleOpen to not be a Button "

- libs/react-components/community/src/components/tooltip/tooltip.module.scss
https://github.com/TEHIK-EE/tedi-design-system/issues/243
> fix(tooltip): add tooltip box shadow change #243

- libs/react-components/tedi/src/components/label/label.tsx
> fix(label): add aria-hidden true to required asterisk label #245

- libs/react-components/src/community/components/button-content/button-content.module.scss
- libs/react-components/src/community/components/toggle-open/toggle-open.stories.tsx
> fix(Anchor, ToggleOpen, Accordion): link toggle-open not rotating #286

- libs/react-components/src/tedi/components/buttons/closing-button/closing-button.tsx
> fix(ClosingButton): add type button #302

- libs/react-components/src/community/components/scroll-fade/scroll-fade.tsx
> fix(scroll-fade): round calculation for scrollToBottom #353

- libs/react-components/src/community/components/form/select/select.module.scss
> feat(select): Align clear icon with tag text #367

- libs/react-components/src/community/components/form/select/select.tsx
https://github.com/TEHIK-EE/tedi-design-system/issues/383
> fix(select): add cacheOptions as a prop for Select

- libs/react-components/src/tedi/components/separator/separator.module.scss
- libs/react-components/src/tedi/components/separator/separator.spec.tsx
- libs/react-components/src/tedi/components/separator/separator.stories.tsx
- libs/react-components/src/tedi/components/separator/separator.tsx
https://github.tehik.ee/tedi-design-system/fix/389-separator-inline-vertical-separator-in-text/react/?path=/docs/tedi-ready-components-helpers-separator--docs
> fix(separator): Inline vertical Separator in text #389

- libs/react-components/src/tedi/components/separator/separator.module.scss
- libs/react-components/src/tedi/components/separator/separator.stories.tsx
example here:
https://github.tehik.ee/tedi-design-system/feat/423-tedi-readycomponentshelpersseparator-add-horizontal-dotted-variant/react/?path=/docs/tedi-ready-components-helpers-separator--docs
> feat(separator): Horizontal dotted variant #423

- libs/react-components/src/tedi/components/form/textarea/textarea.spec.tsx
- libs/react-components/src/tedi/components/form/textarea/textarea.stories.tsx
- libs/react-components/src/tedi/components/form/textarea/textarea.tsx
Changed textarea inner value logic, now uses same logic TextField component.
> fix(textarea): fix inner value #446

- libs/react-components/src/community/components/layout/sidenav/sidenav.module.scss
- libs/react-components/src/community/components/layout/sidenav/sidenav.stories.tsx
- libs/react-components/src/community/components/layout/sidenav/sidenav.tsx
- Add `subItems` property to `SideNavItem` for multilevel menu structure
- Add `showDividers` prop (defaults to `true`) to `SideNavProps` for visual separation options
- Add example of nested navigation in Collapsable story
https://iljakumlander.github.io/tedi-design-system/feat/422-multilevel-sidenav/react/?path=/docs/community-layout-sidenav--docs
> feat(sidenav): Add collapsible navigation with nested items and styling #422

- libs/angular-components/package.json
- libs/angular-components/src/index.ts
- libs/angular-components/src/tedi/components/button/button.component.html
- libs/angular-components/src/tedi/components/button/button.component.scss
- libs/angular-components/src/tedi/components/button/button.component.ts
- libs/angular-components/src/tedi/components/button/button.stories.ts
- libs/angular-components/src/tedi/styles/index.scss
https://github.com/TEHIK-EE/tedi-design-system/issues/516
> feat(button): Add TEDI Angular button #516

- libs/react-components/src/community/components/table/components/table-filter/table-filter.tsx
https://github.com/TEHIK-EE/tedi-design-system/issues/556
> feat(table): update table filter active state #556

- libs/react-components/src/tedi/components/skeleton/skeleton-block/skeleton-block.module.scss
> fix(SkeletonBlock): remove unnecessary 0% from background css #577

- libs/angular-components/community/components/buttons/accordion/accordion-item-content/accordion-item-content.component.html
- libs/angular-components/community/components/buttons/accordion/accordion-item-content/accordion-item-content.component.ts
- libs/angular-components/community/components/buttons/accordion/accordion-item-header/accordion-item-header.component.html
- libs/angular-components/community/components/buttons/accordion/accordion-item-header/accordion-item-header.component.scss
- libs/angular-components/community/components/buttons/accordion/accordion-item-header/accordion-item-header.component.ts
- libs/angular-components/community/components/buttons/accordion/accordion-item/accordion-item.component.html
- libs/angular-components/community/components/buttons/accordion/accordion-item/accordion-item.component.scss
- libs/angular-components/community/components/buttons/accordion/accordion-item/accordion-item.component.ts
- libs/angular-components/community/components/buttons/accordion/accordion.stories.ts
- libs/angular-components/community/components/buttons/accordion/accordion/accordion.component.html
- libs/angular-components/community/components/buttons/accordion/accordion/accordion.component.scss
- libs/angular-components/community/components/buttons/accordion/accordion/accordion.component.ts
- libs/angular-components/community/components/card/card-header/card-header.component.ts
> feat(accordion): Community accordion #552

- libs/angular-components/community/components/form/form-field/form-field.component.scss
- libs/angular-components/community/components/form/form-field/form-field.component.ts
- libs/angular-components/community/components/form/form-field/form-field.stories.ts
- libs/angular-components/community/components/form/index.ts
- libs/angular-components/community/components/form/input/input.component.scss
- libs/angular-components/community/components/form/input/input.component.ts
- libs/angular-components/community/components/form/input/input.stories.ts
ticket: 
https://github.com/TEHIK-EE/tedi-design-system/issues/638
github actions page: 
https://erkidorbek.github.io/tedi-design-system/feature/638-community-form-textfield/angular/?path=/docs/community-angular-form-formfield--docs
> feat(form-text-field): Community form-field & tedi-input directive

- libs/react-components/src/community/components/form/select/select.module.scss
https://github.com/TEHIK-EE/tedi-design-system/issues/695
> feat(select): Community select input bug fix [#695]

- libs/tedi-core/src/variables/_dimensional-variables.scss
Updating list-padding for mobile views.
> fix(tedi-core): update mobile list padding for mobiles

- libs/angular-components/community/components/form/select/select.component.scss
- libs/angular-components/community/components/form/select/select.stories.ts
https://tehikustiilijuhis.slack.com/archives/C08JVSC67C1/p1747301126494329
https://github.com/TEHIK-EE/tedi-design-system/issues/640
> feat(form-select): Add max height and scrollbar to select dropdown #640

- libs/angular-components/community/components/tags/index.ts
- libs/angular-components/community/index.ts
> fix(tag): Adding missing exports for community tag folder #837

- libs/angular-components/tedi/components/layout/footer/footer-body/footer-body.component.ts
- libs/angular-components/tedi/components/layout/footer/footer-bottom/footer-bottom.component.spec.ts
- libs/angular-components/tedi/components/layout/footer/footer-bottom/footer-bottom.component.ts
- libs/angular-components/tedi/components/layout/footer/footer-section/footer-section.component.html
- libs/angular-components/tedi/components/layout/footer/footer-section/footer-section.component.spec.ts
- libs/angular-components/tedi/components/layout/footer/footer-section/footer-section.component.ts
- libs/angular-components/tedi/components/layout/footer/footer-side/footer-side.component.spec.ts
- libs/angular-components/tedi/components/layout/footer/footer-side/footer-side.component.ts
- libs/angular-components/tedi/components/layout/footer/footer.component.spec.ts
- libs/angular-components/tedi/components/layout/footer/footer.component.ts
Quickfixes for sidenav PR:
- #851
> fix(footer): Fix footer tests for sidenav #851

- libs/angular-components/community/components/overlay/modal/modal.component.html
- libs/angular-components/community/components/overlay/modal/modal.component.scss
- libs/angular-components/community/components/overlay/modal/modal.component.ts
- libs/angular-components/community/components/overlay/modal/modal.stories.ts
During component integretion found out that when modal content is too long, the modal itself nor the content was scrollable. Made content of the modal scrollable when modal is too tall
> fix(modal): Added scrollbar and cdkScrollable directive to modal content #776

- libs/angular-components/community/components/overlay/modal/header/modal-header.component.html
Fixes angular content projection.
> fix(modal): Fixed modal content projection #776

- libs/angular-components/community/components/form/select/select.component.ts
Fixes an import. Error came out when installing this in real application.
> feat(community-multiselect): Fix rc8 not building #640

- libs/angular-components/community/components/form/search/search.component.html
- libs/angular-components/community/components/form/search/search.component.ts
- Add ontouched event on search input blur
> fix(community-search): Add ontouched event on input blur #766

- libs/angular-components/.eslintrc.json
- libs/angular-components/community/components/form/file-dropzone/file-dropzone.component.html
- libs/angular-components/community/components/form/file-dropzone/file-dropzone.component.scss
- libs/angular-components/community/components/form/file-dropzone/file-dropzone.component.ts
- libs/angular-components/community/components/form/file-dropzone/file-dropzone.react.scss
- libs/angular-components/community/components/form/file-dropzone/file-dropzone.stories.ts
- libs/angular-components/community/components/form/file-dropzone/file.service.ts
- libs/angular-components/community/components/form/file-dropzone/index.ts
- libs/angular-components/community/components/form/file-dropzone/types.ts
- libs/angular-components/community/components/form/file-dropzone/utils.ts
- libs/angular-components/community/components/form/index.ts
- libs/angular-components/package-lock.json
- libs/angular-components/package.json
- libs/angular-components/tedi/services/translation/translations.ts
https://artur-langl.github.io/tedi-design-system/feat/file-dropzone/angular/?path=/docs/community-angular-form-filedropzone--docs
Also includes change to the eslintrc config to remove a conflict with eslint+prettier caused by brace-style (not possible to fix on this version)
> feat(file-dropzone)

- libs/react-components/src/community/components/layout/header/components/sidenav-toggle/sidenav-toggle.tsx
- libs/react-components/src/community/components/layout/layout-context.ts
- libs/react-components/src/community/components/layout/layout/layout.stories.tsx
- libs/react-components/src/community/components/layout/layout/layout.tsx
[Storybook | Community Layout > With custom menu](https://setsilliksaar.github.io/tedi-design-system-perk/feat/974-layout-community-sidenav-toggle-without-sidenav/react/?path=/story/community-layout--with-custom-menu)
Issue: #974
> feat(layout): Adds to community Layout possibility to use Header Sidenav Toggle to toggle own menu #974

- libs/angular-components/community/components/form/input-group/input-group.component.scss
https://artur-langl.github.io/tedi-design-system/fix/input-group/angular/?path=/docs/community-form-inputgroup--docs
> fix(input-group): remove a style change moving the arrow to the right

- libs/react-components/src/community/components/layout/sidenav/sidenav.tsx
On mobile/tablet (or device mode), tapping a sidenav item closed the menu
immediately on the first touch/pointer event. The synthetic click fired
after the overlay unmounted, leaking through to underlying content and
triggering unintended actions.
Changes:
- Infer external control via `onHeaderSidenavToggle`; if present, do not
close locally (parent handles menu state).
- Defer `toggleMenu()` to the next animation frame on small layouts to let
the click complete within the overlay (prevents leak-through).
- Stop event propagation in item click handler to avoid outside-press
listeners seeing the event.
- Preserve existing desktop behavior; no public API changes or new deps.
> fix(sidenav): prevent ghost-click on touch

- libs/react-components/src/community/components/map-components/map-accordion/map-accordion-item-header.tsx
- libs/react-components/src/community/components/map-components/right-panel/right-panel.tsx
- add showCloseButton prop
- add renderCloseButton override
- remove item from panel on click
- expose onCloseItem callback for side-effects
Closes #1044
> feat(right-panel): make close button configurable and removable

- libs/react-components/src/community/components/vertical-stepper/index.ts
- libs/react-components/src/community/components/vertical-stepper/step-item/step-item.tsx
- libs/react-components/src/community/components/vertical-stepper/sub-item/sub-item.tsx
- libs/react-components/src/community/components/vertical-stepper/vertical-stepper.module.scss
- libs/react-components/src/community/components/vertical-stepper/vertical-stepper.stories.tsx
- libs/react-components/src/community/components/vertical-stepper/vertical-stepper.tsx
- libs/react-components/src/community/index.ts
Desktop-only variant of Vertical-Stepper component.
> feat(vertical-stepper): add vertical stepper component #512
